# Generated by Django 4.2.17 on 2025-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_newslaters"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
